"""empty message

Revision ID: 18010ed6f355
Revises: 43683d7ef792
Create Date: 2021-06-18 16:04:58.431549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18010ed6f355'
down_revision = '43683d7ef792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
