"""empty message

Revision ID: 210ad8fe10bb
Revises: 18010ed6f355
Create Date: 2021-06-18 17:58:49.378296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210ad8fe10bb'
down_revision = '18010ed6f355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privileges', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privileges')
    # ### end Alembic commands ###
